
const char* MAIN_page = "<!DOCTYPE html>"
"<html>"
"<style>"
".card{"
"max-width: 400px;"
"min-height: 500px;"
"background: #02b875;"
"padding: 30px;"
"box-sizing: border-box;"
"color: #FFF;"
"margin:20px;"
"box-shadow: 0px 2px 18px -4px rgba(0,0,0,0.75);"
"}"
"</style>"
"<body>"
"<div class=\"card\">"
"<h1>WuR Multiproto HTTP gateway </h4><br>"
"<button onclick=\"getWake()\">Wake Device</button>"
"<button onclick=\"getData()\">Send Data</button>"
"<h4>Message Status:<span id=\"message_status\">KO</span></h1><br>"
"<h4>Message_result:<span id=\"message_result\"></span></h1><br>"
"<h4>Message time:<span id=\"message_time\">0 ms</span></h1><br>"
"</div>"
"<script>"
"var timestamp = 0;"
"var request_ongoing = false;"
"setInterval(function() {"
"update_timers();"
"}, 100);"
"function getData() {"
"console.log(\"DATA device pressed\");"
"if(request_ongoing){"
"console.log(\"DATA device canceled. Request ongoing\");"
"return;"
"}"
"var xhttp = new XMLHttpRequest();"
"xhttp.onreadystatechange = function() {"
"request_ongoing = false;"
"if (this.readyState == 4 && this.status == 200) {"
"document.getElementById(\"message_status\").innerHTML = \"OK\";"
"}else{"
"document.getElementById(\"message_status\").innerHTML = \"KO\";"
"}"
"};"
"xhttp.open(\"POST\", \"wur/data\", true);"
"xhttp.send();"
"request_ongoing = false;"
"timestamp = Date.now();"
"}"
"function getWake() {"
"console.log(\"WAKE device pressed\");"
"if(request_ongoing){"
"console.log(\"WAKE device canceled. Request ongoing\");"
"return;"
"}"
"var xhttp = new XMLHttpRequest();"
"xhttp.onreadystatechange = function() {"
"request_ongoing = false;"
"if (this.readyState == 4 && this.status == 200) {"
"document.getElementById(\"message_status\").innerHTML = \"OK\";"
"}else{"
"document.getElementById(\"message_status\").innerHTML = \"KO\";"
"}"
"};"
"xhttp.open(\"POST\", \"wur/wake\", true);"
"xhttp.send();"
"request_ongoing = true;"
"timestamp = Date.now();"
"}"
"function update_timers() {"
"if(request_ongoing){"
"var current_time = Date.now();"
"if(timestamp != 0){"
"document.getElementById(\"message_time\").innerHTML = current_time - timestamp;"
"}"
"}"
"}"
"</script>"
"</body>"
"</html>";